"""add new field user_token to user entity

Revision ID: 64facdbf2fdb
Revises: 1b0f4970ea15
Create Date: 2024-02-21 14:43:40.827592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64facdbf2fdb'
down_revision: Union[str, None] = '1b0f4970ea15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_token')
    # ### end Alembic commands ###
